global:
  namespace: clinicflow-staging
  envName: staging
  storageClass: nfs-staging
  ingress:
    enabled: true
    className: nginx
    host: clinicflow-staging.192.168.60.200.nip.io
    tls:
      enabled: true
      secretName: clinicflow-staging-tls
replicas:
  identity: 2
  scheduling: 2
  profiles: 2
  notifications: 2
  web: 2
postgres:
  common:
    storageSize: 10Gi
  identity:
    enabled: true
    dbName: identity_db
    user: identity_user
    password: identity_staging_pw
  scheduling:
    enabled: true
    dbName: scheduling_db
    user: scheduling_user
    password: scheduling_staging_pw
  profiles:
    enabled: true
    dbName: profiles_db
    user: profiles_user
    password: profiles_staging_pw
  notifications:
    enabled: true
    dbName: notifications_db
    user: notifications_user
    password: notifications_staging_pw
webConfig:
  NEXT_PUBLIC_IDENTITY_API: "/identity"
  NEXT_PUBLIC_SCHEDULING_API: "/scheduling"
  NEXT_PUBLIC_PROFILES_API: "/profiles"
  NEXT_PUBLIC_NOTIFICATIONS_API: "/notifications"
appConfig:
  identity:
    CORS_ORIGINS: ""
  scheduling:
    CORS_ORIGINS: ""
    NOTIFICATIONS_BASE_URL: "http://clinicflow-notifications:3004"
  profiles:
    CORS_ORIGINS: ""
  notifications:
    CORS_ORIGINS: ""
images:
  identity:
    tag: "sha-a53d753"
  scheduling:
    tag: "v1"
  profiles:
    tag: "v2"
  notifications:
    tag: "v1"
  web:
    tag: "v1"
