global:
  namespace: clinicflow-prod
  envName: prod
  storageClass: nfs-prod
  ingress:
    enabled: true
    className: nginx
    host: clinicflow.192.168.60.111.nip.io
    tls:
      enabled: true
      secretName: clinicflow-prod-tls
replicas:
  identity: 2
  scheduling: 2
  profiles: 2
  notifications: 2
  web: 2
postgres:
  common:
    storageSize: 20Gi
  identity:
    enabled: true
    dbName: identity_db
    user: identity_user
    password: identity_prod_pw
  scheduling:
    enabled: true
    dbName: scheduling_db
    user: scheduling_user
    password: scheduling_prod_pw
  profiles:
    enabled: true
    dbName: profiles_db
    user: profiles_user
    password: profiles_prod_pw
  notifications:
    enabled: true
    dbName: notifications_db
    user: notifications_user
    password: notifications_prod_pw
webConfig:
  NEXT_PUBLIC_IDENTITY_API: "/identity"
  NEXT_PUBLIC_SCHEDULING_API: "/scheduling"
  NEXT_PUBLIC_PROFILES_API: "/profiles"
  NEXT_PUBLIC_NOTIFICATIONS_API: "/notifications"
appConfig:
  identity:
    CORS_ORIGINS: ""
  scheduling:
    CORS_ORIGINS: ""
    NOTIFICATIONS_BASE_URL: "http://clinicflow-notifications:3004"
  profiles:
    CORS_ORIGINS: ""
  notifications:
    CORS_ORIGINS: ""
images:
  identity:
    tag: "sha-096dfab"
  scheduling:
    tag: "sha-096dfab"
  profiles:
    tag: "v2"
  notifications:
    tag: "sha-096dfab"
  web:
    tag: "sha-096dfab"
