apiVersion: v1
kind: Service
metadata:
  name: clinicflow-identity
  namespace: {{ include "clinicflow.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  type: ClusterIP
  selector:
    app: clinicflow-identity
  ports:
    - name: http
      port: {{ .Values.ports.identity }}
      targetPort: {{ .Values.ports.identity }}
