apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinicflow-identity
  namespace: {{ include "clinicflow.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: {{ .Values.replicas.identity }}
  selector:
    matchLabels:
      app: clinicflow-identity
  template:
    metadata:
      labels:
        app: clinicflow-identity
        {{- include "clinicflow.labels" . | nindent 8 }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: identity
          image: "{{ .Values.images.identity.repository }}:{{ .Values.images.identity.tag }}"
          ports:
            - containerPort: {{ .Values.ports.identity }}
          env:
            - name: PORT
              value: {{ .Values.ports.identity | quote }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: identity-db-secret
                  key: DATABASE_URL
            - name: CORS_ORIGINS
              value: {{ .Values.appConfig.identity.CORS_ORIGINS | quote }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: identity-app-secret
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ports.identity }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ports.identity }}
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources.defaults | nindent 12 }}
