{{- if .Values.global.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clinicflow-api-ingress
  namespace: {{ include "clinicflow.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    kubernetes.io/ingress.class: {{ .Values.global.ingress.className | quote }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
spec:
  {{- if .Values.global.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.global.ingress.host | quote }}
      secretName: {{ .Values.global.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.global.ingress.host | quote }}
      http:
        paths:
          - path: {{ printf "%s(/|$)(.*)" .Values.global.ingress.paths.identity | quote }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: clinicflow-identity
                port:
                  number: {{ .Values.ports.identity }}

          - path: {{ printf "%s(/|$)(.*)" .Values.global.ingress.paths.scheduling | quote }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: clinicflow-scheduling
                port:
                  number: {{ .Values.ports.scheduling }}

          - path: {{ printf "%s(/|$)(.*)" .Values.global.ingress.paths.profiles | quote }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: clinicflow-profiles
                port:
                  number: {{ .Values.ports.profiles }}

          - path: {{ printf "%s(/|$)(.*)" .Values.global.ingress.paths.notifications | quote }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: clinicflow-notifications
                port:
                  number: {{ .Values.ports.notifications }}
{{- end }}
