{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: profiles-migrate
  namespace: {{ include "clinicflow.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: Replace=true
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        {{- include "clinicflow.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never

      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}

      initContainers:
        - name: wait-for-db
          image: postgres:16-alpine
          command: ["sh", "-lc"]
          args:
            - |
              until pg_isready -h profiles-db -p 5432; do
                echo "Waiting for profiles-db..."
                sleep 2
              done

      containers:
        - name: migrate
          image: "{{ .Values.images.profiles.repository }}:{{ .Values.images.profiles.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: profiles-db-secret
                  key: DATABASE_URL
          command: ["sh", "-lc"]
          args:
            - "./node_modules/.bin/prisma migrate deploy"
{{- end }}
