{{- if .Values.postgres.profiles.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: profiles-db
  namespace: {{ include "clinicflow.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: profiles-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: profiles-db
  namespace: {{ include "clinicflow.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  serviceName: profiles-db
  replicas: 1
  selector:
    matchLabels:
      app: profiles-db
  template:
    metadata:
      labels:
        app: profiles-db
        {{- include "clinicflow.labels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 999
        fsGroupChangePolicy: "OnRootMismatch"

      containers:
        - name: postgres
          image: {{ .Values.postgres.common.image }}
          ports:
            - containerPort: 5432

          securityContext:
            runAsUser: 999
            runAsGroup: 999

          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          envFrom:
            - secretRef:
                name: profiles-db-secret

          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.global.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.postgres.common.storageSize | quote }}
{{- end }}
